In [1]:
# Importing the required libraries
import pandas as pd
import numpy as np


# Given dictionary data
data = {
    'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills','Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
    'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
    'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
    'priority': ['yes', 'yes', 'no', 'yes', 'no','no', 'no', 'yes', 'no', 'no']
}

# Given index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

##### 1. Create a DataFrame birds from this dictionary data which has the index labels.

In [2]:
# pd.DataFrame() converts dictionary data into a DataFrame
# index=labels gives custom row labels
birds = pd.DataFrame(data, index=labels)

birds

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

##### 2. Display a summary of the basic information about birds DataFrame and its data.

In [3]:
# info() displays information such as: number of rows, columns, data types and memory usage
birds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birds     10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

##### 3. Print the first 2 rows of the birds dataframe

In [4]:
# head(n) returns the first n rows
birds.head(2)

    birds  age  visits priority
a  Cranes  3.5       2      yes
b  Cranes  4.0       4      yes

##### 4. Print all the rows with only 'birds' and 'age' columns from the dataframe

In [5]:
# [['birds', 'age']] selects only these two columns

birds[['birds', 'age']]

        birds  age
a      Cranes  3.5
b      Cranes  4.0
c     plovers  1.5
d  spoonbills  NaN
e  spoonbills  6.0
f      Cranes  3.0
g     plovers  5.5
h      Cranes  NaN
i  spoonbills  8.0
j  spoonbills  4.0

##### 5. select [2, 3, 7] rows and in columns ['birds', 'age', 'visits']

In [6]:
# iloc[] selects rows using their position numbers
# 2, 3 and 7 represent the 3rd, 4th and 8th rows
birds.iloc[[2, 3, 7]][['birds', 'age', 'visits']]

        birds  age  visits
c     plovers  1.5       3
d  spoonbills  NaN       4
h      Cranes  NaN       2

##### 6. select the rows where the number of visits is less than 4

In [7]:
# birds['visits'] < 4 creates a condition
# Only rows satisfying the condition are selected
birds[birds['visits'] < 4]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

##### 7. select the rows with columns ['birds', 'visits'] where the age is missing i.e NaN

In [8]:
# isna() checks for missing/NaN values
# loc[] selects rows and required columns
birds.loc[birds['age'].isna(), ['birds', 'visits']]

        birds  visits
d  spoonbills       4
h      Cranes       2

##### 8. Select the rows where the birds is a Cranes and the age is less than 4

In [9]:
# == checks whether the bird is Cranes
# < 4 checks whether age is less than 4
birds[(birds['birds'] == 'Cranes') & (birds['age'] < 4)]

    birds  age  visits priority
a  Cranes  3.5       2      yes
f  Cranes  3.0       4       no

##### 9. Select the rows the age is between 2 and 4(inclusive)

In [10]:
# between(2, 4) selects values from 2 to 4
birds[birds['age'].between(2, 4)]

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
f      Cranes  3.0       4       no
j  spoonbills  4.0       2       no

##### 10. Find the total number of visits of the bird Cranes

In [11]:
# First select only Cranes
# Then select their visits
# sum() calculates the total
total_visits = birds[birds['birds'] == 'Cranes']['visits'].sum()

print("Total visits of Cranes:", total_visits)

Total visits of Cranes: 12

##### 11. Calculate the mean age for each different birds in dataframe.

In [12]:
# groupby() groups rows according to bird type
# mean() calculates the average age of each group
mean_age = birds.groupby('birds')['age'].mean()

print(mean_age)

birds
Cranes        3.5
plovers       3.5
spoonbills    6.0
Name: age, dtype: float64

##### 12. Append a new row 'k' to dataframe with your choice of values for each column. Then delete that row to return the original DataFrame.

In [13]:
# loc[] can be used to add a new row
birds.loc['k'] = ['eagle', 5, 3, 'yes']

print("After adding row k:")
print(birds)

# drop() removes the specified row
birds = birds.drop('k')

print("\nAfter deleting row k:")
print(birds)

After adding row k:
        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k       eagle  5.0       3      yes

After deleting row k:
        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

##### 13. Find the number of each type of birds in dataframe (Counts)

In [14]:
# value_counts() counts how many times each value occurs
bird_count = birds['birds'].value_counts()

print(bird_count)

birds
Cranes        4
spoonbills    4
plovers       2
Name: count, dtype: int64

##### 14. Sort dataframe (birds) first by the values in the 'age' in decending order, then by the value in the 'visits' column in ascending order.

In [15]:
# sort_values() sorts the DataFrame
# age -> descending order (False)
# visits -> ascending order (True)
sorted_birds = birds.sort_values(by=['age', 'visits'],ascending=[False, True])
print(sorted_birds)

        birds  age  visits priority
i  spoonbills  8.0       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
j  spoonbills  4.0       2       no
b      Cranes  4.0       4      yes
a      Cranes  3.5       2      yes
f      Cranes  3.0       4       no
c     plovers  1.5       3       no
h      Cranes  NaN       2      yes
d  spoonbills  NaN       4      yes

##### 15. Replace the priority column values with'yes' should be 1 and 'no' should be 0

In [16]:
# map() replaces values according to the given dictionary
birds['priority'] = birds['priority'].map({'yes': 1,'no': 0})
birds

        birds  age  visits  priority
a      Cranes  3.5       2         1
b      Cranes  4.0       4         1
c     plovers  1.5       3         0
d  spoonbills  NaN       4         1
e  spoonbills  6.0       3         0
f      Cranes  3.0       4         0
g     plovers  5.5       2         0
h      Cranes  NaN       2         1
i  spoonbills  8.0       3         0
j  spoonbills  4.0       2         0

##### 16. In the 'birds' column, change the 'Cranes' entries to 'trumpeters'.

In [18]:
birds['birds'] = birds['birds'].replace('Cranes','trumpeters')
birds

        birds  age  visits  priority
a  trumpeters  3.5       2         1
b  trumpeters  4.0       4         1
c     plovers  1.5       3         0
d  spoonbills  NaN       4         1
e  spoonbills  6.0       3         0
f  trumpeters  3.0       4         0
g     plovers  5.5       2         0
h  trumpeters  NaN       2         1
i  spoonbills  8.0       3         0
j  spoonbills  4.0       2         0