In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import combinations

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("BSS.csv")
data

    BP  Age  Score Sex
0  124   22     65   M
1  117   33     34   F
2  127   35     35   M
3  132   44     43   M
4  117   42     54   F
5  122   52     60   F
6  119   62     60   F
7  134   65     42   M

In [4]:
data['Sex'] = data['Sex'].map({"M":1, "F":0})
data

    BP  Age  Score  Sex
0  124   22     65    1
1  117   33     34    0
2  127   35     35    1
3  132   44     43    1
4  117   42     54    0
5  122   52     60    0
6  119   62     60    0
7  134   65     42    1

In [5]:
X = data[['Age', 'Score', 'Sex']]
X

   Age  Score  Sex
0   22     65    1
1   33     34    0
2   35     35    1
3   44     43    1
4   42     54    0
5   52     60    0
6   62     60    0
7   65     42    1

In [6]:
Y = data['BP']
Y

0    124
1    117
2    127
3    132
4    117
5    122
6    119
7    134
Name: BP, dtype: int64

In [7]:
N = len(Y)
print("N:",N)
p = X.shape[1]
print("P:",p)

N: 8
P: 3

In [8]:
X.columns

Index(['Age', 'Score', 'Sex'], dtype='object')

In [9]:
res = []
for k in range(1, p+1):
    for features in combinations(X.columns, k):
        model = LinearRegression()
        model.fit(X[list(features)], Y)
        Y_Pred = model.predict(X[list(features)])
        rss = np.sum((Y - Y_Pred) ** 2)
        res.append([k, features, rss])

print(res)

[[1, ('Age',), 281.40558346372404], [1, ('Score',), 272.89369456931115], [1, ('Sex',), 79.5], [2, ('Age', 'Score'), 251.7281577395088], [2, ('Age', 'Sex'), 22.06823661098674], [2, ('Score', 'Sex'), 77.27817450012992], [3, ('Age', 'Score', 'Sex'), 19.817650186665595]]

In [10]:
res = pd.DataFrame(res, columns=["K", "Best Predictors", "RSS"])
res

   K    Best Predictors         RSS
0  1             (Age,)  281.405583
1  1           (Score,)  272.893695
2  1             (Sex,)   79.500000
3  2       (Age, Score)  251.728158
4  2         (Age, Sex)   22.068237
5  2       (Score, Sex)   77.278175
6  3  (Age, Score, Sex)   19.817650

In [11]:
best = res.loc[res["RSS"].idxmax()]
best["Best Predictors"]

('Age',)

In [12]:
res = []
for k in range(1, p+1):
    for features in combinations(X.columns, k):
        model = LinearRegression()
        model.fit(X[list(features)], Y)
        Y_Pred = model.predict(X[list(features)])
        rss = np.sum((Y - Y_Pred) ** 2)
    res.append([k, features, rss])

print(res)

[[1, ('Sex',), 79.5], [2, ('Score', 'Sex'), 77.27817450012992], [3, ('Age', 'Score', 'Sex'), 19.817650186665595]]

In [13]:
res = pd.DataFrame(res, columns=["K", "Best Predictors", "RSS"])
res

   K    Best Predictors        RSS
0  1             (Sex,)  79.500000
1  2       (Score, Sex)  77.278175
2  3  (Age, Score, Sex)  19.817650

In [14]:
lowest_aic = float("inf")
for k, features, rss in res.values:
    aic = N*np.log(rss/N) + 2*k
    print(aic)
    if aic < lowest_aic:
        lowest_aic = aic
print(lowest_aic)

20.370523839843603
22.143760208421572
13.257051380060759
13.257051380060759

In [15]:
lowest_bic = float("inf")
for k, features, rss in res.values:
    bic = N*np.log(rss/N) + k*np.log(N)
    print(bic)
    if bic < lowest_bic:
        lowest_bic = bic
print(lowest_bic)

20.449965381523437
22.302643291781244
13.495376005100265
13.495376005100265